<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exercice Require</title>
    <link rel="stylesheet" href="assets/styles/style.css">
</head>
<body>
    <?php require 'templates/partials/_header.phtml'; ?>
    <?php require 'templates/partials/_main.phtml'; ?>
    <?php require 'templates/partials/_footer.phtml'; ?>
</body>
</html>
